language: go
go:
  - 1.12.4

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - GO111MODULE=on
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=ddns-route53
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=ddns-route53
    - secure: hSD2tZ+nTYU6cSW5RjnRsr+SkN567xTe61tE1Tp7Nw+tWSX0v6hIWs/OWSPHAGl88AhA5hmjShSSZ6HvHaONG0XV+snJxn4yG0HT44rOaL4loa2C/FrZ8wllfuiuLJTn0Ub+7LZnc6xwA9sYM0NI/HcSKJbn0jOm3vBp4DS0QZ5U0ci72CNIPIFKxOuGEj2BQEWNILVKn434eb3agDdsPgR7fpN9QAQMaXJAlGyphfZeHTCEOZPayzrCdkzKZoDZLVVNMr6Dhu3+ZWcKioy/NAy75gw79ncmgvnNSa3R7xVprgiqKSGJIZIFrv5JCSZ5776dg/t0vfUb4b50ti8HuUtkNzTkdnIP4YEbWFtnQnVor86LON1stffnHRUUGVpiRt9H7MIuXcpJsDzgKut9Y+AWpbkkqFVgERIeXfJwNmBYMRZARA5CKa5qK9oi62q9BKnt06iKIX5sBjQeI2ShRascTpmd8dW63aVW2/7AMJn9LIrAqq/ga26F3ZKVcplA48YQfz151tzUI5KYBD5c7COsMPoy27g6PZ9e2h4lzmUwTNO4a4PF8S5272pmITmnZwKho0iPRxKpztxPvlCzc6kqJqNVqfPSNMpyBAvocW0Q/WCNrAFhK7PigIbhxqJMbk/Kux4d06vYKZIIQMImFusY2E8u2ZJFhGxu43w6918= # DOCKER_PASSWORD
    - secure: ODdO2uT5vklD7XTLaJFafjgSpWrgCM27kD4ASBUw89/XQsJ6Kfa0bAxw0cZQoK128aSONf+/uqu+gsDT0CG5e0TDL1mDEjskTY1Sw2VVFVjGSYgrk93rnMzfwwap9q3jC8HRqmo1+FZcrBD+fCRO9JlwgKl/YnrMB0u5/mvKDAWxSgAV8CMDJiwG1Kp2eD8OOFSjG9ueLamBwIzW3o9b4FmDisStBcGrkdcPwoqk6TF3slZn2L7eOrg3oPWjvP9Wqi3P02jeXC/rUeKo6V8d4qgLG6FwZ0Sv17qsvwnwdWaUvfYQuj+tXFHPrZ95cQUIWjE9G+J03hK2fXNwA7E5Uph7E4BWQvx1kiMti4Aqz7YYA1BknVuzfvO/nGBeWvwn/QVvaeSpEJzMgHOBpzjyqXhlZQM6Nl57ilRLevJNVSpTLBteYeiiOT96KIltaRrWoaFjWQ8kZ/m3bFoQqWTQWy+D2jww5p3qwB/n5AhQZ7kca1lcERi2wnTeY/hD5KfnzDyllkn85Qv8Yxs9yOuiFNruqUkRTkZffzcnSo2jPw8X/dTfXxsTfNLfEvPtYjVCyDx7I4bwCm1Em13N17EXyvIqRYnoT+VUflz3ZVapi/fHpLGCvqdru3PVjcsZWJFJ1RPGgOvdh1aSusfrecHAqrBgEUBGWDhhcLRb6dg07GA= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

install:
  - curl -sL https://git.io/goreleaser | head -n -2 | bash
  - tar -xf /tmp/goreleaser.tar.gz -C $GOPATH/bin
  - goreleaser -v

script: ./build.sh

deploy:
  provider: releases
  api_key:
    secure: kdpOUPTK463KIXrBexy3Fp/GYWuX6h4G8bw14kACkvuu4zVLrBx28T+r+RonIEKCtMTqaNAgIpNrQ7Bi3udSwh8N9YzcA5YrS1QFcEK6OicG3ZfvsP8UgK+OzKlg82TRiMxZO77NehzDOIVSesteCnbBZydep+AFvSD1vTUI228sOYGgJQ/PfCdE/6udEQ5rdsxLFa75iJuin4WZq1ahrXc/6hKuruRsCNMOsvLXpPjMIz0V4PQ9uEhigSNrOiAfn8IupSjt0TpkoC4syLTD7XtDIpJ3BJOZkxRMU6KX+8kLwamd25k+ySGPBskzVeJXw1qSWlld3IwpBilVm7VTozKvJWNHcTOiQnWLCGCwWTZ/+goX92P4tcNXFmw1JmimjA0WXupbo5p2FkUi4u+I6WW5ZJ3tgMT1CGQWdcE6t0DVOxgEJ3v2Z4xJhWN3Eir4G71yZsTNi4EmBYbB7B4RZyoZaNDPG6q7davjahc5NFapq7DPzF0bJUqOCBasAZmjMb/k5m55Tie9bOPaDhp8inl16EfUq/+Keg/bP0OLS2eGldhXJIc66YXNZ7Ndt7WxhzlbMO178Nsz0pMyhTm8aNE1Xak6nllqKDMy4+NU07NjwPkeaJSmQX2sXEkBS6N3tppvRj6vB9HJUxG24r7gDBnfK/cR2h00wXFD1c3XHiQ=
  file_glob: true
  file:
    - dist/checksums.txt
    - dist/*.tar.gz
    - dist/*.zip
  skip_cleanup: true
  draft: true
  on:
    tags: true
