version: "3.2"

services:
  ddns-route53:
    image: crazymax/ddns-route53:latest
    container_name: ddns-route53
    volumes:
      - "./ddns-route53.yml:/ddns-route53.yml:ro"
    environment:
      - "TZ=Europe/Paris"
      - "SCHEDULE=*/30 * * * *"
      - "MAX_RETRIES=3"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "LOG_CALLER=false"
      #- AWS_ACCESS_KEY_ID=
      #- AWS_SECRET_ACCESS_KEY=
      #- AWS_HOSTED_ZONE_ID=
    restart: always
