name: gosum

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/gosum.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      -
        name: Tidy
        run: |
          rm -f go.sum
          go mod tidy
      -
        name: Commit changes
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { readFileSync } = require('fs');
            const { resolve } = require('path');
            const { execSync } = require('child_process');

            const changedFiles = execSync('git diff --name-only').toString().split('\n').filter(Boolean);
            if (changedFiles.length == 0) {
              core.info('No changes');
              return;
            }

            const parentSha = execSync('git rev-parse HEAD').toString().trim();
            const tree = await github.git.createTree({
              ...context.repo,
              base_tree: parentSha,
              tree: changedFiles.map(path => ({
                path,
                mode: '100644',
                content: readFileSync(resolve(process.cwd(), path), 'utf8')
              }))
            });

            const commit = await github.git.createCommit({
              ...context.repo,
              message: 'Fix go.sum',
              tree: tree.data.sha,
              parents: [parentSha]
            });

            await github.git.createRef({
              ...context.repo,
              ref: github.context.ref,
              sha: commit.data.sha
            });
